#Simple Calculator(*Very Simple*)
# 85 Approx Lines Code
''' Made By Jigar Maurya'''
_FullStop = ('.')
_FirstNum = str(input('Enter first number: \n'))
_SecondNum = str(input('Enter second number: \n'))
_Operator = str(input('Enter the operator(you want to use): \n'))
_FirstNum1 = int(_FirstNum)
_SecondNum1 = int(_SecondNum)
_Operator1 = str(_Operator)
_FirstNum2 = _FirstNum.lower()
_SecondNum2 = _SecondNum.lower()
if (('+') in _Operator1):
    _Syntax1 = ('The sum of')
    _Syntax2 = ('and')
    _Syntax3 = ('is')
    _Sum = ((_FirstNum1) + (_SecondNum1))
    _Sum1 = str(_Sum)
    _Sum2 = ((_Sum1) + (_FullStop))
    print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Sum2)
elif (('-') in _Operator1):
    _Syntax1 = ('The subtraction of')
    _Syntax2 = ('and')
    _Syntax3 = ('gives')
    _Sub = ((_FirstNum1) - (_SecondNum1))
    _Sub1 = str(_Sub)
    _Sub2 = ((_Sub1) + (_FullStop))
    print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Sub2)
elif (('*') in _Operator1):
    _Syntax1 = ('The multiplication of')
    _Syntax2 = ('and')
    _Syntax3 = ('gives')
    _Mul = ((_FirstNum1) * (_SecondNum1))
    _Mul1 = str(_Mul)
    _Mul2 = ((_Mul1) + (_FullStop))
    print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Mul2)
elif (('/') in _Operator1):
    _Syntax1 = ('The division of')
    _Syntax2 = ('and')
    _Syntax3 = ('gives')
    _Div = ((_FirstNum1) / (_SecondNum1))
    _Div1 = str(_Div)
    _Div2 = ((_Div1) + (_FullStop))
    print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Div2)
else:
    print("The Operator You Entered Is Wrong(Please Try again!!)")  
    _Operator = str(input('Enter the operator(you want to use): \n'))
    _FirstNum1 = int(_FirstNum)
    _SecondNum1 = int(_SecondNum)
    _Operator1 = str(_Operator)
    _FirstNum2 = _FirstNum.lower()
    _SecondNum2 = _SecondNum.lower()
    if (('+') in _Operator1):
        _Syntax1 = ('The sum of')
        _Syntax2 = ('and')
        _Syntax3 = ('is')
        _Sum = ((_FirstNum1) + (_SecondNum1))
        _Sum1 = str(_Sum)
        _Sum2 = ((_Sum1) + (_FullStop))
        print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Sum2)
    elif (('-') in _Operator1):
        _Syntax1 = ('The subtraction of')
        _Syntax2 = ('and')
        _Syntax3 = ('gives')
        _Sub = ((_FirstNum1) - (_SecondNum1))
        _Sub1 = str(_Sub)
        _Sub2 = ((_Sub1) + (_FullStop))
        print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Sub2)
    elif (('*') in _Operator1):
        _Syntax1 = ('The multiplication of')
        _Syntax2 = ('and')
        _Syntax3 = ('gives')
        _Mul = ((_FirstNum1) * (_SecondNum1))
        _Mul1 = str(_Mul)
        _Mul2 = ((_Mul1) + (_FullStop))
        print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Mul2)
    elif (('/') in _Operator1):
        _Syntax1 = ('The division of')
        _Syntax2 = ('and')
        _Syntax3 = ('gives')
        _Div = ((_FirstNum1) / (_SecondNum1))
        _Div1 = str(_Div)
        _Div2 = ((_Div1) + (_FullStop))
        print(_Syntax1, _FirstNum1, _Syntax2, _SecondNum1, _Syntax3, _Div2) 
    else:
        print('''Sorry, The operator you entered is invalid again.
(Run The Program *AGAIN* for using it)
Bye!!''') 
